Flex Box
eylemdemir/web-exercises pull request #5
Opened 2024-03-12 10:49 UTC by eylemdemir

2024-03-18 08:11 UTC, eylemdemir commented
i did add my Media-queries  and i change my photo position with flexbox

2024-03-25 21:52 UTC, maks-io requested changes
Prinzipiell sieht es gut aus, ich frage mich aber wozu du die media-queries in `mediaSC.css` eingebaut hast - der `body` ändert sich optisch gar nicht?

2024-03-25 22:05 UTC, eylemdemir commented
dear markus, 
when my max width between 400px and 600px my button and list became column-reverse and  my font sizes became small. for others i didnt want change background color and so on cuz i like this look. i wrote for practice. should i change?

2024-03-26 09:12 UTC, maks-io approved these changes

2024-03-26 09:14 UTC, merged